### ISSUE TITLE
package.json missing dependency

### ISSUE THREAD

**Issue by EdHintz** [BandwidthExamples/node-voice-reference-app#1]
After npm install and running node index.js, I received the following error:

The file "/Users/edbandwidth/code/node-voice-reference-app/node_modules/thenify-all/node_modules/thenify/index.js" requires `Promise`,
but neither `bluebird` nor the native `Promise` implementation were found.
Please install `bluebird` yourself.

Looks like you need to do the following:
npm install bluebird --save

**Comment by avbel** [comment]
or use latest stable node (0.12+)

2015-05-28 16:00 GMT+03:00 EdHintz <notifications@github.com>:

**Comment by avbel** [comment]
I added a note about node 0.10 to README.md.
